<?php
/**
 * Created by PhpStorm.
 * User: lulongwen
 * Date: 2019-07-04
 * Time: 21:51
 * 基础控制器
 */
namespace frontend\controllers;

use yii\web\Controller;

class BaseController extends Controller {
  public function beforeAction($action)
  {
    // if (!parent::beforeAction($action)) return false;
    // return true;
    return parent ::beforeAction($action);
    // TODO: Change the autogenerated stub
  }
}